import { IPerson } from './person';
import { ProposalAccessibilty } from './proposal-accessibilty';
import { ProposalType } from './proposal-type';

export interface IProposal {
  _id?: string;
  title: string;
  summary: string;
  glossaries: string[];
  responsibles: IPerson[];
  contacts: IPerson[];
  createdAt: string;
  registeredAt: string;
  deadline: string;
  electionPeriod: string;
  createdBy: string;
  type: ProposalType;
  accessibility: ProposalAccessibilty;
  responsibleDepartment: string;
}

export interface autoGeneratedProposalParts {
  title: string;
  summary: string;
  glossaries: string[];
  contacts?: string[];
  responsibleDepartment?: string;
}
