import { IGlossary } from './glossary';
import { IPerson } from './person';
import { ProposalAccessibilty } from './proposal-accessibilty';
import { ProposalType } from './proposal-type';

export interface IProposal {
  id: number;
  title: string;
  summary: string;
  glossaries: IGlossary[];
  responsible: IPerson;
  contacts: IPerson[];
  createdAt: Date;
  registeredAt: Date;
  deadline: Date;
  electionPeriod: string;
  createdBy: string;
  type: ProposalType;
  accessibility: ProposalAccessibilty;
}

export interface autoGeneratedProposalParts {
  title: string;
  summary: string;
  glossaries: string[];
  contacts?: string[];
} 
