import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { environment } from '../../environments/environment';
import { autoGeneratedProposalParts } from '../interfaces/proposal';
import { IProposal } from './../interfaces/proposal';

@Injectable({
  providedIn: 'root',
})
export class ProposalService {
  constructor(private readonly http: HttpClient) {}

  public getProposals(): Observable<IProposal[]> {
    return this.http.get<IProposal[]>(environment.apiUrl + '/proposals');
  }

  public getProposalById(id: number): Observable<IProposal> {
    return this.http.get<IProposal>(environment.apiUrl + `/proposals/${id}`);
  }

  public uploadProposalFile(
    file: FormData
  ): Observable<autoGeneratedProposalParts> {
    console.log(file);
    return this.http.post<autoGeneratedProposalParts>(
      environment.apiUrl + '/upload',
      file
    );
  }

  public createProposal(
    proposal: IProposal,
    file: FormData
  ): Observable<IProposal> {
    return this.http.post<IProposal>(
      environment.apiUrl + '/createProposal',
      proposal
    );
  }
}
