services:
  api:
    build: 
      dockerfile: ./api/Dockerfile
    ports:
      - "8000:8000"
    volumes:
    - ./api:/app
    # volumes:
    #   - .:/app
    # develop:
    #   watch:
    #     - action: sync+restart
    #       path: ./src
    #       target: /app/src
    #     - action: rebuild
    #       path: requirements.txt
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

volumes:
  frontend:
  api: